name: Test runner disk space

on:
    push:

jobs:
    test-disk-space:
        runs-on: ubuntu-latest
        steps:
            - name: Print beginning disk space before checkout
              run: df -h
            - name: See what memory we have
              run: free -h
            - name: Checkout
              uses: actions/checkout@v4
            - name: Print beginning disk space after checkout
              uses: ./.github/actions/print-disk-space
            - name: See what's in the mnt directory
              run: | 
                ls -lh /mnt
                cat /mnt/DATALOSS_WARNING_README.txt
