name: Test runner disk space

on:
    push:

jobs:
    test-disk-space:
        runs-on: ubuntu-latest
        steps:
            - name: Print beginning disk space before checkout
              run: df -h
            - name: See what memory we have
              run: free -h
            - name: Maximize build space
              uses: AdityaGarg8/remove-unwanted-software@v4.1
              with:
                remove-android: 'true'
                remove-docker-images: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
            - name: Checkout
              uses: actions/checkout@v4
            - name: Print disk space after checkout
              uses: ./.github/actions/print-disk-space
            - name: See what's in the mnt directory
              run: | 
                ls -lh /mnt
                cat /mnt/DATALOSS_WARNING_README.txt
            - name: Install OS packages required for build
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                packages: cmake curl clang pkg-config libssl-dev libpq-dev libdw-dev binutils lld libudev-dev
                version: 1.0 # This is a cache key -- change it when you change the package list above
            - name: Print disk space after package install
              uses: ./.github/actions/print-disk-space
            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: 1.78.0
                components: clippy, rustfmt
            - name: Print disk space after rust toolchain install
              uses: ./.github/actions/print-disk-space
            - name: Checkout target project repo
              uses: actions/checkout@v4
              with:
                repository: aptos-labs/aptos-core
                path: './aptos-core'
            - name: Print disk space after checkout target repo
              uses: ./.github/actions/print-disk-space
            - name: Build target project
              continue-on-error: true
              run: |
                sudo mkdir /mnt/cargo-target
                sudo chown $(whoami) /mnt/cargo-target
                cd ./aptos-core
                CARGO_TARGET_DIR=/mnt/cargo-target cargo build
            - name: Print disk space after checkout build
              uses: ./.github/actions/print-disk-space
