name: Test runner disk space

on:
    push:

jobs:
    test-disk-space:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Print beginning disk space
              run: df -h
